=== mborysiak-sp/PlatformaDystrybucjiCyfrowej/form.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT products (games|films|e-books|music)*>
        <!ELEMENT games (game)*>
        <!ELEMENT game (name|price|publisher|developer|categories)*>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ATTLIST price
                currency CDATA #IMPLIED
                currencys CDATA #IMPLIED>
        <!ELEMENT publisher (#PCDATA)>
        <!ELEMENT developer (#PCDATA)>
        <!ELEMENT categories (category)*>
        <!ELEMENT category (#PCDATA)>
        <!ELEMENT films (film)*>
        <!ELEMENT film (name|price|director|distributor|length|genres)*>
        <!ELEMENT director (#PCDATA)>
        <!ELEMENT distributor (#PCDATA)>
        <!ELEMENT length (#PCDATA)>
        <!ATTLIST length
                unit CDATA #REQUIRED>
        <!ELEMENT genres (genre)*>
        <!ELEMENT genre (#PCDATA)>
        <!ELEMENT e-books (e-book)*>
        <!ELEMENT e-book (name|price|author|pages|genres)*>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT pages (#PCDATA)>
        <!ELEMENT music (album)*>
        <!ELEMENT album (name|price|artist|length|genres)*>
        <!ELEMENT artist (#PCDATA)>

=== mborysiak-sp/PlatformaDystrybucjiCyfrowej/database.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/css" href="style.css" ?>
<!DOCTYPE products SYSTEM "form.dtd">
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="form.xsd">
    <games>
        <game>
            <name>Skyrim 1: Arena</name>
            <price currency="euro">14,88</price>
            <publisher>Bethesda</publisher>
            <developer>Bethesda</developer>
            <genres>
                <genre>FPS</genre>
                <genre>RPG</genre>
            </genres>
        </game>
        <game>
            <name>Skyrim 2: Daggerfall</name>
            <price currency="euro">14,88</price>
            <publisher>Bethesda</publisher>
            <developer>Bethesda</developer>
            <genres>
                <genre>RTS</genre>
                <genre>RPG</genre>
            </genres>
        </game>
        <game>
            <name>Skyrim 3: Morrowind</name>
            <price currency="euro">1488</price>
            <publisher>Bethesda</publisher>
            <developer>Bethesda</developer>
            <genres>
                <genre>FPS</genre>
                <genre>RPG</genre>
            </genres>
        </game>
        <game>
            <name>Skyrim 4: Oblivion</name>
            <price currency="euro">21,37</price>
            <publisher>Bethesda</publisher>
            <developer>Bethesda</developer>
            <genres>
                <genre>RTS</genre>
            </genres>
        </game>
        <game>
            <name>Skyrim 5: Widełorecenzja</name>
            <price currency="euro">14,88</price>
            <publisher>KlocuchVideos</publisher>
            <developer>Klocuch</developer>
            <genres>
                <genre>4X</genre>
                <genre>Strategy</genre>
            </genres>
        </game>
    </games>
    <films>
        <film>
            <name>Bóg nie umarł</name>
            <price currency="euro">14,88</price>
            <director>Peter Jackson</director>
            <distributor>Universal</distributor>
            <length unit="minute">110</length>
            <genres>
                <genre>Thriller</genre>
            </genres>
        </film>
        <film>
            <name>Bóg nie umarł 2 Electric Boogaloo</name>
            <price currency="euro">128</price>
            <director>Steven Spielberg</director>
            <distributor>Universal</distributor>
            <length unit="minute">150</length>
            <genres>
                <genre>Comedy</genre>
            </genres>
        </film>
        <film>
            <name>Bóg jednak umarł</name>
            <price currency="euro">11</price>
            <director>Fryderyk Nicowski</director>
            <distributor>Zarathustra</distributor>
            <length unit="minute">120</length>
            <genres>
                <genre>Horror</genre>
                <genre>Thriller</genre>
            </genres>
        </film>
        <film>
            <name>Pitbull. Niebezpieczni Mężczyźni</name>
            <price currency="euro">14,88</price>
            <director>Patrick Vegas</director>
            <distributor>Vegas Productions</distributor>
            <length unit="minute">120</length>
            <genres>
                <genre>Action</genre>
                <genre>Gangster</genre>
            </genres>
        </film>
        <film>
            <name>Smerfy: Poszukiwacze zaginionej wioski</name>
            <price currency="euro">14,88</price>
            <director>James Gargamel</director>
            <distributor>Cauldron Productions</distributor>
            <length unit="minute">90</length>
            <genres>
                <genre>Fantasy</genre>
                <genre>Occultism</genre>
            </genres>
        </film>
    </films>
    <e-books>
        <e-book>
            <name>Таня Гроттер и Золотая Пиявка</name>
            <price currency="euro">30</price>
            <author>J.K. Rowling</author>
            <pages>100</pages>
            <genres>
                <genre>Fantasy</genre>
                <genre>Occultism</genre>
            </genres>
        </e-book>
        <e-book>
            <name>Wiedźmin: Powrót Vesemira</name>
            <price currency="euro">20</price>
            <author>Andrew Sapkowsky</author>
            <pages>200</pages>
            <genres>
                <genre>Science fiction</genre>
            </genres>
        </e-book>
        <e-book>
            <name>Harri Potta</name>
            <price currency="euro">14,88</price>
            <author>J.K. Rowlong</author>
            <pages>416</pages>
            <genres>
                <genre>Adventure</genre>
                <genre>Comedy</genre>
            </genres>
        </e-book>
    </e-books>
    <music>
        <album>
            <name>W dzień triumfu nad złem</name>
            <price currency="euro">121,88</price>
            <artist>Honor</artist>
            <length unit="minute">90</length>
            <genres>
                <genre>Classical music</genre>
                <genre>Jazz</genre>
            </genres>
        </album>
        <album>
            <name>The Satanist</name>
            <price currency="euro">18</price>
            <artist>Behemoth</artist>
            <length unit="minute">45</length>
            <genres>
                <genre>Hard rock</genre>
                <genre>Blues</genre>
            </genres>
        </album>
        <album>
            <name>First and Last and Always</name>
            <price currency="euro">10</price>
            <artist>Sisters of Mercy</artist>
            <length unit="minute">50</length>
            <genres>
                <genre>Gothic Rock</genre>
                <genre>Alternative</genre>
            </genres>
        </album>
    </music>
</products>
